spring.application.name=api-gateway

server.port=8080

# ===============================
# Eureka
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ===============================
# Auth Service Route
# ===============================
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

# ===============================
# Shipment Service Route
# ===============================
spring.cloud.gateway.server.webflux.routes[1].id=shipment-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://SHIPMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/shipments/**

# ===============================
# JWT
# ===============================
jwt.secret=swift_dispatch_logistics_jwt_super_secret_key_2026_klu_soa_security_key_must_be_long_enough

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.gateway.access=read-only